# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: livejournal 0.3.10 ruby lib

Gem::Specification.new do |s|
  s.name = "livejournal2".freeze
  s.version = "0.4.1"
  s.licenses    = ['MIT']
  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Evan Martin".freeze, "Roman Shterenzon".freeze, "Vitalii Khustochka".freeze]
  s.date = "2021-03-27"
  s.description = "LiveJournal API client. Fork of the original livejournal gem. Post to livejournal, retrieve friends lists, edit entries, sync journal to an offline database.".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Changes",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/livejournal.rb",
    "lib/livejournal/basic.rb",
    "lib/livejournal/comment.rb",
    "lib/livejournal/comments-xml.rb",
    "lib/livejournal/database.rb",
    "lib/livejournal/entry.rb",
    "lib/livejournal/friends.rb",
    "lib/livejournal/login.rb",
    "lib/livejournal/logjam.rb",
    "lib/livejournal/request.rb",
    "lib/livejournal/sync.rb",
    "sample/export",
    "sample/fuse",
    "sample/graph",
    "sample/progressbar.rb",
    "setup.rb",
    "test/checkfriends.rb",
    "test/comments-xml.rb",
    "test/database.rb",
    "test/login.rb",
    "test/roundtrip.rb",
    "test/time.rb"
  ]
  s.homepage = "https://github.com/khustochka/livejournal2".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Module for interacting with Livejournal API".freeze
end
